spring:
  application:
    name: msvc-configParametro
  config:
    import: optional:configserver:http://localhost:8888
  jackson:
    serialization:
      fail-on-empty-beans: false
logging:
  level:
    org:
      springframework:
        test:
          context:
            cache: debug
