server:
  port: 8081

spring:
  application:
    name: auth-user-rol
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://fonafe.database.windows.net;databaseName=pruebaFonafe;trustServerCertificate=false
    username: devFonafe19
    password: joshueLobo95!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    org:
      hibernate:
        sql: debug
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka