server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: ms-fonafe.azurewebsites.net
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://ms-fonafe.azurewebsites.net:${server.port}/eureka