eureka:
  client:
    register-with-eureka: false

server:
  port: 8080
spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v01/**
          filters:
            - AuthFilter
        - id: auth-user-rol
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**