server:
  port: 8085

spring:
  application:
    name: msvc-plantillasReport
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=pruebaFonafe;trustServerCertificate=true
    username: joshueLobo
    password: nuevaContra95!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    org:
      hibernate:
        sql: debug
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka