eureka:
  client:
    register-with-eureka: false

server:
  port: 8080
spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v01/**
        - id: auth-user-rol
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: privil
          uri: http://localhost:8082
          predicates:
            - Path=/pr/**
          filters:
            - AuthFilter
        - id: configParametro
          uri: http://localhost:8083
          predicates:
            - Path=/listaParametros/**
          filters:
            - AuthFilter
        - id: proyectos
          uri: http://localhost:8084
          predicates:
            - Path=/proyecto/**
          filters:
            - AuthFilter
        - id: plantillaDocumentos
          uri: http://localhost:8085
          predicates:
            - Path=/estructuraDocumento/**
          filters:
            - AuthFilter